- hosts: all
  tasks:
  - name: Copy needed conf and cred files 
    yum: 
      name: ceph-common
      state: present 

  - name: Create Bench User Credentials 
    shell: |
      radosgw-admin user create --uid=bench --display-name=bench --access-key=bench --secret=bench 
    register: result

  - name: Print test result if OK
    debug:
      msg: "Created a Bench user!"
    when: result is succeeded
