- hosts: localhost
  tasks:
  - name: Copy needed files 
    shell: | 
      sshpass -p "password" scp root@{{ inventory_hostname }}:/etc/ceph/ceph.conf /etc/ceph/
      sshpass -p "password" scp root@{{ inventory_hostname }}:/etc/ceph/ceph.client.admin.keyring /etc/ceph/
  - name: Create Bench User Credentials 
    shell: |
      radosgw-admin user create --uid=bench --display-name=bench --access-key=bench --secret=bench 
    register: result
    delegate_to: localhost

  - name: Print test result if OK
    debug:
      msg: "Created a Bench user!"
    when: result is succeeded
    delegate_to: localhost
