apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: amq
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: '2.6'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 3
      transaction.state.log.replication.factor: 3
    listeners:
      plain: {}
    replicas: 3
    storage:
      class: ocs-external-storagecluster-ceph-rbd
      deleteClaim: true
      size: 5Gi
      type: persistent-claim
    version: 2.6.0
  zookeeper:
    replicas: 1
    storage:
      class: ocs-external-storagecluster-ceph-rbd
      deleteClaim: true
      size: 5Gi
      type: persistent-claim
