apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: webapp
  name: prometheus-webapp-monitor
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      interval: 30s
      port: metrics
      scheme: http
      path: /
  namespaceSelector:
    matchNames:
      - rafael-monitoring
  selector:
    matchLabels:
      app: webapp
